### ISSUE TITLE
系统的表结构呢

### ISSUE THREAD

**Issue by gitama2016** [doodooke/doodooke#1]

**Comment by einsqing** [comment]
数据库表结构是migrate自动生成的，具体参考knex migrate

**Comment by gitama2016** [comment]
> 
> 
> 数据库表结构是migrate自动生成的，具体参考knex migrate



> 
> 
> 数据库表结构是migrate自动生成的，具体参考knex migrate

不是安装的时候自动生成的么，，？？还是要自己弄

**Comment by einsqing** [comment]
安装成功，自动插入数据库
